### ISSUE TITLE
快捷方式添加Xposed Edge Pro的通知功能是闪退

### ISSUE THREAD

**Issue by iduee** [Webb-L/NotificationFilterAndroid#1]
java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=453426122, result=-1, data=Intent { (has extras) }} to activity {top.webb_l.notificationfilter/top.webb_l.notificationfilter.ui.activity.local.rules.RuleEditActivity}: java.lang.NullPointerException: intent.categories must not be null
	at android.app.ActivityThread.deliverResults(ActivityThread.java:5628)
	at android.app.ActivityThread.handleSendResult(ActivityThread.java:5667)
	at android.app.servertransaction.ActivityResultItem.execute(ActivityResultItem.java:67)
	at android.app.servertransaction.ActivityTransactionItem.execute(ActivityTransactionItem.java:45)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2415)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:211)
	at android.os.Looper.loop(Looper.java:300)
	at android.app.ActivityThread.main(ActivityThread.java:8401)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:559)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:954)
Caused by: java.lang.NullPointerException: intent.categories must not be null
	at big$e.a(Unknown Source:283)
	at big$e.q(Unknown Source:2)
	at b6$a.c(Unknown Source:6)
	at b6$a.a(Unknown Source:0)
	at a6.onActivityResult(Unknown Source:2)
	at z5.d(Unknown Source:22)
	at z5.b(Unknown Source:24)
	at androidx.activity.ComponentActivity.onActivityResult(Unknown Source:2)
	at android.app.Activity.dispatchActivityResult(Activity.java:8923)
	at android.app.ActivityThread.deliverResults(ActivityThread.java:5621)
	... 13 more

**Comment by Webb-L** [comment]
应该是这个快捷方法不能添加
